repos:
  - repo: https://github.com/prettier/prettier
    rev: 1.17.0
    hooks:
      - id: prettier

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.7
    hooks:
      - id: remove-crlf

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      # check config files are parsable
      - id: check-xml
      - id: check-toml
      - id: check-json
      - id: check-yaml
      # check merge errors
      - id: check-merge-conflict
      # code quality
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: double-quote-string-fixer
