backend:
  name: github
  repo: GuillaumeC86/blowcycles # Path to your GitHub repository
  # optional, defaults to master
  branch: master


# These lines should *not* be indented
media_folder: 'src/assets/images'

# Use branches and merge requests
publish_mode: editorial_workflow

# Internationalization
# i18n:
#   structure: multiple_folders
#   locales: [fr, en]
#   default_locale: fr

collections:
  - name: 'config'
    label: 'Config'
    editor:
      preview: false
    files:
    - name: 'navigation'
      label: 'Navigation'
      file: 'src/_data/navigation.yml'
      fields:
        - label: 'Table of Contents'
          name: 'toc'
          widget: 'list'
          fields:
            - { label: Title, name: title, widget: string }
            - { label: Pages, name: pages, widget: list, fields: [{ label: Page, name: page, widget: string }, { label: URL, name: link, widget: string }] }
  - name: 'pages'
    label: 'Pages'
    folder: 'src/pages'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Permalink', name: 'permalink', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'page' }
    editor:
      preview: false

  - name: prices
    label: Prices
    files:
    - name: 'pricing_cards'
      label: 'Pricing Cards'
      file: 'src/_data/pricing_cards.yml'
      fields:
      - { name: title, label: Title, widget: string }
      - { name: description, label: Description, widget: text }
      - { name: price, label: Price, widget: string }
      - { name: items, label: Items, widget: list, fields: [
          { name: text, label: Text, widget: string },
          { name: icon, label: Icon, widget: string },
        ]}
