backend:
  name: gitlab
  repo: blowcycles/blowcycles # Path to your GitHub repository
  # optional, defaults to master
  branch: master
  auth_type: pkce # Required for pkce
  app_id: 3fd72faff01fe745a9a6c5950387f92ad2be32533402abea998e891d061de86f # Application ID from your GitLab settings


# These lines should *not* be indented
media_folder: 'src/assets/images'

# Use branches and merge requests
publish_mode: editorial_workflow

# Internationalization
# i18n:
#   structure: multiple_folders
#   locales: [fr, en]
#   default_locale: fr

collections:
  - name: "pages"
    label: "Pages"
    folder: "src/pages"
    create: true
    slug: "{{slug}}"
    filter: {field: "editable", value: true}
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Editable", name: "editable", widget: "hidden", default: true}
      - { label: "Permalink", name: "permalink", widget: "string", default: "/my-link/" }
      - {
          label: "Layout",
          name: "layout",
          widget: "select",
          default: "markdown",
          options: ['markdown', 'default']
        }
      - label: "Body"
        name: "body"
        widget: "markdown"

  - name: 'homepage'
    label: 'Homepage'
    editor:
      preview: false
    files:
    - name: 'hero'
      label: 'Hero Content'
      file: 'src/_data/hero.yml'
      fields:
        - { name: 'title', label: 'Hero Title', widget: 'string' }
        - { name: 'description', label: 'Hero Description', widget: 'text' }
        - { name: 'image', label: 'Hero Image', widget: 'image' }
        - { name: 'button.label', label: 'Hero Button Label', widget: 'string' }
        - { name: 'button.url', label: 'Hero Button URL', widget: 'string' }
    - name: 'features'
      label: 'Features'
      file: 'src/_data/features.yml'
      fields:
        - { name: 'features', label: 'Features', widget: 'list', fields: [
            { name: 'icon', label: 'Icon', widget: 'string' },
            { name: 'title', label: 'Title', widget: 'string' },
            { name: 'description', label: 'Description', widget: 'text' }
          ]}
    - name: 'pricing_cards'
      label: 'Pricing Cards'
      file: 'src/_data/pricing_cards.yml'
      fields:
        - { name: 'title', label: 'Pricing Cards Title', widget: 'string' }
        - { name: 'description', label: 'Pricing Cards Description', widget: 'text' }
        - { name: 'background_image', label: 'Pricing Cards Background Image', widget: 'image' }
        - { name: 'cards', label: 'Pricing Cards', widget: 'list', fields: [
            { name: 'title', label: 'Title', widget: 'string' },
            { name: 'description', label: 'Description', widget: 'text' },
            { name: 'price', label: 'Price', widget: 'string' },
            { name: 'items', label: 'Items', widget: 'list', fields: [
                { name: 'text', label: 'Text', widget: 'string' },
                { name: 'icon', label: 'Icon', widget: 'string' }
              ]}
          ]}
    - name: 'opening_closing_days'
      label: 'Opening/Closing Days'
      file: 'src/_data/opening_closing_days.yml'
      fields:
        - { name: 'opening_days', label: 'Opening Days', widget: 'list', field: { name: 'date', label: 'YYYY-MM-DD', widget: 'string' } }
        - { name: 'closing_days', label: 'Closing Days', widget: 'list', field: { name: 'date', label: 'YYYY-MM-DD', widget: 'string' } }
  - name: "configuration"
    label: "Website Configuration"
    files:
      - name: "config"
        label: "Config"
        file: "src/_data/config.yml"
        fields:
          - { label: "Address", name: "address", widget: "string" }
          - { label: "Phone", name: "phone", widget: "string" }
          - { label: "Email", name: "email", widget: "string" }
          - label: "GPS"
            name: "gps"
            widget: "object"
            fields:
              - { label: "Latitude", name: "latitude", widget: "string" }
              - { label: "Longitude", name: "longitude", widget: "string" }
          - label: "Social"
            name: "social"
            widget: "object"
            fields:
              - { label: "Facebook", name: "facebook", widget: "string" }
              - { label: "Instagram", name: "instagram", widget: "string" }
              - { label: "Twitter", name: "twitter", widget: "string" }
              - { label: "Github", name: "github", widget: "string" }
      - name: "navbar"
        label: "Navbar"
        file: "src/_data/navigation.yml"
        fields:
          - name: navigation
            label: Navigation
            widget: list
            fields:
              - { label: "Displayed Title", name: "text", widget: "string" }
              - { label: "Link", name: "url", widget: "string", default: "/" }
  - name: 'our_bikes'
    label: 'Our Bikes'
    editor:
      preview: false
    files:
    - name: 'our_bikes'
      label: 'Our Bikes'
      file: 'src/_data/our_bikes.yml'
      fields:
        - { name: 'title', label: 'Title', widget: 'string' }
        - { name: 'description', label: 'Description', widget: 'text' }
        - { name: 'bikes', label: 'Bikes', widget: 'list', fields: [
            { name: 'title', label: 'Title', widget: 'string' },
            { name: 'description', label: 'Description', widget: 'text' },
            { name: 'image', label: 'Image', widget: 'image' }
          ]}
