# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Blow Cycles
lang: fr
email: blowcycles@gmail.com
tagline: Location & vente de vélos à assistance électrique
description: >- # this means to ignore newlines until "baseurl:"
  Location et vente de vélos à assistance électrique en gare de Fontainebleau-Avon.
  Vélos tout-terrains adaptés à l'exploration de la forêt de Fontainebleau, casques VTT inclus dans la location,
  carte de la forêt avec points de vue à découvrir. Demi-journée ou journée complète.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blowcycles.com" # the base hostname & protocol for your site, e.g. http://example.com

social:
  name: Blow Cycles
  links:
    - https://twitter.com/blowcycles
    - https://www.facebook.com/BlowCycles
    - https://www.instagram.com/blowcycles

instagram_username: blowcycles
facebook_username: BlowCycles
twitter_username: blowcycles

twitter:
  username: blowcycles
  card: summary

logo: /assets/images/logo_full.svg

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
