name: Deploy Jekyll Website

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3  # Specify the Ruby version you need for your gems

      - name: Install Jekyll and dependencies
        run: |
          sudo gem install bundler
          sudo gem install jekyll
          cd src
          bundle install
          npm install

      - name: Build Jekyll website
        run: |
          cd src
          bundle exec jekyll build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./src/_site
          cname: blowcycles.com
          enable_jekyll: true
